name: performance_profiler
description: A Flutter package for profiling performance, including screen load time, FPS, and widget rebuild tracking.
version: 1.0.2+
repository: https://github.com/MahmoudShawky1612/performance_profiler
issue_tracker: https://github.com/MahmoudShawky1612/performance_profiler/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  path_provider: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
